service: buses

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-south-1
  stage: ${opt:stage, 'dev'}
  profile: personal
  role: arn:aws:iam::343547439778:role/myplanner-lambda-role
  environment:
    REGION: ${self:provider.region}
    STAGE: ${self:provider.stage}

resources:
  Resources:
    DynamoEventBus:
      Type: AWS::Events::EventBus
      Properties:
        Name: ${self:provider.stage}-db-event-bus

    # treatment_plan event queue
    inviteEventQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "invite-event-${self:provider.stage}"
        VisibilityTimeout: 180
        MessageRetentionPeriod: 1209600
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt:
              - inviteEventDeadQueue
              - Arn
          maxReceiveCount: 3

    inviteEventDeadQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "invite-event-dead-${self:provider.stage}"
        MessageRetentionPeriod: 1209600

    inviteEventPolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        PolicyDocument:
          Statement:
            - Action: "SQS:SendMessage"
              Effect: "Allow"
              Resource: !GetAtt inviteEventDeadQueue.Arn
              Principal:
                Service: events.amazonaws.com
              Condition:
                ArnEquals:
                  "aws:SourceArn": !GetAtt inviteEventRule.Arn
        Queues:
          - !Ref inviteEventQueue

    inviteEventRule:
      Type: AWS::Events::Rule
      Properties:
        Name: inviteEventRule
        Description: rule to project data change
        EventBusName: !GetAtt DynamoEventBus.Name
        Targets:
          - Arn: !GetAtt inviteEventQueue.Arn
            Id: inviteEventQueueId
        EventPattern:
          source:
            - "dynamo-stream"
          detail:
            itemType:
              - project-invite
            eventName:
              - INSERT
              - MODIFY
  
  Outputs:
    DBEventBusName:
      Value: !Ref DynamoEventBus
      Export:
        Name: ${self:provider.stage}-db-event-bus-name
    inviteEventQueueArn:
      Value: !GetAtt inviteEventQueue.Arn
      Export:
        Name: ${self:provider.stage}-inviteEventQueueArn